package debugger;

import casplan.Base;
import casplan.object.*;
import casplan.object.Function.BPType;
import java.util.HashMap;
import java.awt.*;
import javax.swing.JTextPane;
import javax.swing.SwingUtilities;
import javax.swing.text.*;
import javax.swing.tree.DefaultMutableTreeNode;

public class Debugger extends javax.swing.JDialog {
  public Debugger(java.awt.Frame parent, boolean modal) {
    super(parent, modal);
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    stopButton = new javax.swing.JButton();
    continueButton = new javax.swing.JButton();
    stepButton = new javax.swing.JButton();
    stepIntoButton = new javax.swing.JButton();
    stepFromButton = new javax.swing.JButton();
    treeView = new javax.swing.JScrollPane();
    tree = new javax.swing.JTree();
    codeView = new javax.swing.JScrollPane();
    code = new JTextPane() {
      public void paintComponent(Graphics g) {
        super.paintComponent(g);

        Graphics2D g2 = (Graphics2D) g;

        g2.setColor(new Color(255, 0, 0, 128));

        FontMetrics fm = getFontMetrics(getFont());
        int x = fm.charWidth('w') * (function.column - 1);
        int y = fm.getHeight() * (function.line - 1) + 2;
        g2.fillRect(x, y, getWidth() - x, 4);

        g2.dispose();
      }

      public boolean getScrollableTracksViewportWidth() {
        return getUI().getPreferredSize(this).width 
        <= getParent().getSize().width;
      }
    };

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setModal(true);
    setName(""); // NOI18N
    setSize(new java.awt.Dimension(640, 606));

    stopButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/casplan/icons/control-stop-square.png"))); // NOI18N
    stopButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        stopButtonActionPerformed(evt);
      }
    });

    continueButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/casplan/icons/control.png"))); // NOI18N
    continueButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        continueButtonActionPerformed(evt);
      }
    });

    stepButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/casplan/icons/arrow.png"))); // NOI18N
    stepButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        stepButtonActionPerformed(evt);
      }
    });

    stepIntoButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/casplan/icons/arrow-turn-270.png"))); // NOI18N
    stepIntoButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        stepIntoButtonActionPerformed(evt);
      }
    });

    stepFromButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/casplan/icons/arrow-turn-090-left.png"))); // NOI18N
    stepFromButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        stepFromButtonActionPerformed(evt);
      }
    });

    treeView.setPreferredSize(new java.awt.Dimension(160, 322));

    javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("root");
    tree.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
    treeView.setViewportView(tree);

    code.setFont(new java.awt.Font("Monospaced", 0, 13)); // NOI18N
    codeView.setViewportView(code);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addComponent(codeView, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)
        .addGap(0, 0, 0)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(treeView, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addGroup(layout.createSequentialGroup()
            .addComponent(stopButton)
            .addGap(0, 0, 0)
            .addComponent(continueButton)
            .addGap(0, 0, 0)
            .addComponent(stepButton)
            .addGap(0, 0, 0)
            .addComponent(stepIntoButton)
            .addGap(0, 0, 0)
            .addComponent(stepFromButton))))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
            .addComponent(stepIntoButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(stepFromButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
          .addComponent(stepButton)
          .addComponent(stopButton)
          .addComponent(continueButton))
        .addGap(0, 0, 0)
        .addComponent(treeView, javax.swing.GroupLayout.DEFAULT_SIZE, 581, Short.MAX_VALUE))
      .addComponent(codeView)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void stepButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stepButtonActionPerformed
    function.setNextBreakpoint(context, BPType.STEP);
    dispose();
  }//GEN-LAST:event_stepButtonActionPerformed

  private void continueButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continueButtonActionPerformed
    dispose();
  }//GEN-LAST:event_continueButtonActionPerformed

  private void stopButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopButtonActionPerformed
    System.exit(0);
  }//GEN-LAST:event_stopButtonActionPerformed

  private void stepIntoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stepIntoButtonActionPerformed
    function.setNextBreakpoint(context, BPType.STEP_INTO);
    dispose();
  }//GEN-LAST:event_stepIntoButtonActionPerformed

  private void stepFromButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stepFromButtonActionPerformed
    function.setNextBreakpoint(context, BPType.STEP_OUT);
    dispose();    
  }//GEN-LAST:event_stepFromButtonActionPerformed
    
  public static void execute(Context context, Function function) {
    function.removeBreakpoint();
    Debugger dialog = new Debugger(new javax.swing.JFrame(), true);
    dialog.context = context;
    dialog.function = function;
    dialog.init();
    dialog.setVisible(true);
  }
    
  DefaultMutableTreeNode root;
  
  public void init() {
    setModal(true);
    setTitle("Debugger");
    addWindowListener(new java.awt.event.WindowAdapter() {
      @Override
      public void windowClosing(java.awt.event.WindowEvent e) {
        dispose();
      }
    });
    
    Rectangle bounds = GraphicsEnvironment.getLocalGraphicsEnvironment()
        .getMaximumWindowBounds();
    setSize(640, bounds.height);
    setLocation(bounds.width - 640, 0);
    
    code.setText(function.source.text.toString());
    
    SwingUtilities.invokeLater(() -> {
      FontMetrics fm = code.getFontMetrics(code.getFont());
      codeView.getVerticalScrollBar().setValue(function.line * fm.getHeight()
          - codeView.getHeight() / 2);
    });
    
    

    root = (DefaultMutableTreeNode) tree.getModel().getRoot();
    
    Context ctx = context;
    while(ctx != null && ctx.functionCall != null) {
      UserFunction userFunction = ctx.function;
      DefaultMutableTreeNode node = addNode(root
          , ctx.functionCall.getCaption());
      for(int index = 0; index < ctx.params.length; index++) {
        if(ctx.params[index] == null) continue;
        addNode(node, userFunction.vars[index].name + ": "
            + ctx.params[index].toString());
      }
      
      ctx = ctx.prevContext;
    }
      
    DefaultMutableTreeNode global = addNode(root, "main");
    for(Variable var : Base.globalVariables.values()) {
      addFieldNode(global, var.name, var.value);
    }
    
    for(int i = 0; i < tree.getRowCount(); i++) tree.expandRow(i);
  }  
  
  static DefaultMutableTreeNode addNode(DefaultMutableTreeNode parent
      , String caption) {
    DefaultMutableTreeNode node = new DefaultMutableTreeNode(caption);
    if(parent != null) parent.add(node);
    return node;
  }
  
  static void addFieldNode(DefaultMutableTreeNode parent, String caption
      , CasObject value) {
    if(value == null || value.toString().equals("")) return;
    DefaultMutableTreeNode node = addNode(parent, caption + ": "
        + value.toString());
    if(value.isUserObject()) {
      for(HashMap.Entry<Field, CasObject> entry : value.toUserObject()
          .values.entrySet()) {
        addFieldNode(node, entry.getKey().name, entry.getValue());
      }
    }
    
    if(value.isList()) {
      int index = 0;
      for(CasObject item : value.toList().items) {
        addFieldNode(node, String.valueOf(index), item);
        index++;
      }
    }
  }
  
  private Function function;
  private Context context;
  
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JTextPane code;
  private javax.swing.JScrollPane codeView;
  private javax.swing.JButton continueButton;
  private javax.swing.JButton stepButton;
  private javax.swing.JButton stepFromButton;
  private javax.swing.JButton stepIntoButton;
  private javax.swing.JButton stopButton;
  private javax.swing.JTree tree;
  private javax.swing.JScrollPane treeView;
  // End of variables declaration//GEN-END:variables
}
